name: hello-test
on:
  push:
    branches:
    - main
jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout code
        uses: actions/checkout@v4
      
      - name: Show message and list file
        run: |
          echo "$(cat hello.txt)"
          ls -lh
